# SPDX-License-Identifier: GPL-3.0-or-later
# Virtual camera for the OnePlus 5 (see ~/.local/bin/phonecam).
# The scrcpy camera stream is written to /dev/video10.
# exclusive_caps=1 is required so that Chromium/WebRTC accept the device as a
# camera: the device reports capture capability only while a producer
# (the camera stream) has it open.
options v4l2loopback video_nr=10 card_label="PhoneCam Camera" exclusive_caps=1
